"""UserscriptGen v0.5.8 - Generate + validate Tampermonkey scripts for self-evo tests.

Produces installable userscripts that can talk to GitHub (SELF-EVOLVE companion style)
and validates structure for measurable CI/local tests. Results feed EverythingDB.
"""

from __future__ import annotations

import hashlib
import re
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


class UserscriptGenerator:
    """Generates compact, self-updating Tampermonkey scripts."""

    def __init__(self):
        self.metrics = {"generated": 0, "validated": 0, "bytes": 0}
        self.last_script: str = ""

    def generate(
        self,
        features: Optional[List[str]] = None,
        name: str = "Singularity Self-Evo Companion",
        version: str = "0.5.8",
        match: str = "*://github.com/*",
    ) -> str:
        if features is None:
            features = [
                "auto-status",
                "evolution-report-hook",
                "groq-ready",
                "fleet-ping",
            ]
        feature_list = ", ".join(features)
        script = f"""// ==UserScript==
// @name         {name}
// @namespace    https://github.com/eric847b/singularity-operator
// @version      {version}
// @description  Autonomous companion: {feature_list}. Generated by UserscriptGen v{version}.
// @author       Singularity Operator
// @match        {match}
// @grant        GM_xmlhttpRequest
// @grant        GM_setValue
// @grant        GM_getValue
// @connect      api.github.com
// @run-at       document-idle
// ==/UserScript==

(() => {{
  "use strict";
  const VERSION = "{version}";
  const FEATURES = {features!r};
  const log = (e) => console.debug("[Singularity-Userscript]", e);

  const status = () => ({{
    version: VERSION,
    features: FEATURES,
    path: location.pathname,
    repo: location.pathname.split("/").slice(1, 3).join("/"),
    ts: Date.now(),
  }});

  // Fleet ping: expose for console / SELF bridge
  window.SINGULARITY_USERSCRIPT = {{
    version: VERSION,
    status,
    features: FEATURES,
    ping: () => {{
      const s = status();
      log({{ ping: s }});
      return s;
    }},
  }};

  // Lightweight evolution report hook (posts nothing without token)
  window.SINGULARITY_USERSCRIPT.report = (summary) => {{
    log({{ report: String(summary).slice(0, 200) }});
    return {{ ok: true, queued: false, note: "set GH_TOKEN via companion for live post" }};
  }};

  setTimeout(() => log({{ loaded: true, ...status() }}), 1500);
  console.log("[Singularity-Userscript] v" + VERSION + " loaded — window.SINGULARITY_USERSCRIPT ready");
}})();
"""
        self.last_script = script
        self.metrics["generated"] += 1
        self.metrics["bytes"] = len(script)
        return script

    def validate(self, script: Optional[str] = None) -> Dict[str, Any]:
        """Structural validation — measurable without a browser."""
        src = script if script is not None else self.last_script
        checks = {
            "has_userscript_header": "// ==UserScript==" in src and "// ==/UserScript==" in src,
            "has_match": "@match" in src,
            "has_grant": "@grant" in src,
            "has_iife": "(() =>" in src or "(function" in src,
            "has_window_export": "window.SINGULARITY_USERSCRIPT" in src or "window.SELF" in src,
            "min_length": len(src) >= 200,
        }
        ok = all(checks.values())
        digest = hashlib.sha256(src.encode()).hexdigest()[:16] if src else ""
        if ok:
            self.metrics["validated"] += 1
        return {
            "ok": ok,
            "checks": checks,
            "bytes": len(src),
            "sha256_16": digest,
            "timestamp": _utc_now(),
        }

    def run_self_evo_test(self, features: Optional[List[str]] = None) -> Dict[str, Any]:
        """Generate + validate — the measurable userscript self-evo test."""
        script = self.generate(features=features)
        validation = self.validate(script)
        return {
            "suite": "userscript_self_evo",
            "generated": True,
            "validation": validation,
            "preview": script[:240].replace("\n", " "),
            "metrics": self.get_metrics(),
            "timestamp": _utc_now(),
        }

    def get_metrics(self) -> Dict[str, Any]:
        return dict(self.metrics)

    def summary_line(self) -> str:
        m = self.metrics
        return f"UserscriptGen: generated={m.get('generated', 0)} validated={m.get('validated', 0)} bytes={m.get('bytes', 0)}"


print("UserscriptGenerator v0.5.8 - Generate + validate self-evo scripts ready")
